name: giraffe
channels:
  - conda-forge
  - pytorch
  - nvidia
  - pyg
dependencies:
  - click
  - configparser
  - ipython 
  - matplotlib
  - opentsne
  - pip  
  - polaris
  - pyg=*=*cu121
  - python=3.12
  - pytorch-cuda=12.1
  - seaborn
  - pip:
    - tensorboard
